name: Final Zed Windows Build and Archival Notice

on:
  workflow_dispatch: # Allows for one final manual run

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Zed Source Code for Final Build (v0.208.4)
        uses: actions/checkout@v4
        with:
          repository: zed-industries/zed
          ref: v0.208.4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-v0.208.4-${{ hashFiles('**/Cargo.lock') }}

      - name: Build Zed (Release v0.208.4)
        run: cargo build --release

      - name: Package Executable
        id: package
        shell: pwsh
        run: |
          $exePath = "target/release/zed.exe"
          $zipFileName = "zed-windows-v0.208.4.zip"
          if (Test-Path $exePath) {
            Compress-Archive -Path $exePath -DestinationPath $zipFileName
            echo "Packaged final build into $zipFileName"
            echo "ASSET_PATH=$zipFileName" >> $env:GITHUB_OUTPUT
            echo "ASSET_NAME=$zipFileName" >> $env:GITHUB_OUTPUT
          } else {
            echo "Error: Could not find built executable at $exePath"
            exit 1
          }

      - name: Create Final GitHub Release (v0.208.4)
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "${{ steps.package.outputs.ASSET_PATH }}"
          tag: "v0.208.4"
          name: "Final Unofficial Build - Zed for Windows v0.208.4"
          body: |
            **This is the final unofficial build from this repository.** 🎉

            Official Zed builds for Windows are now available! A huge thank you to everyone who used and supported this project.

            **Please head over to the [Official Zed Releases Page](https://github.com/zed-industries/zed/releases) to get the latest versions.**

            This repository will now be archived. Thank you for your support!

            ---

            *This final build corresponds to the official Zed release tag **v0.208.4***.
          allowUpdates: true # Allow updating the release if it already exists
          makeLatest: true